#trigger: none
trigger:
- main
pr: none

pool: 'Azure Pipelines'

stages:
- stage: FirstStage
  jobs:
  - job: FirstStageFirstJob
    steps:
    - bash: |
        echo "So damn, let's start"
      name: dummy_step
    - bash: |
        SOME_VAR="bla-bla-bla"
        echo "set output pipeline variable:"
        echo "##vso[task.setvariable variable=firstJobVar;isOutput=true]${SOME_VAR}"
        echo "firstJobVar scope is job wide: 'firstJobVar' value is ${firstJobVar}"
      name: set_output_variable
    - bash: |
        echo $(set_output_variable.firstJobVar)
      name: access_output_variable

  - job: SecondJob
    dependsOn: ['FirstStageFirstJob']
    variables:
      secondJobVar: $[ dependencies.FirstStageFirstJob.outputs['set_output_variable.firstJobVar'] ] 
    steps:      
    - bash: |
        echo "The value of the dinamic pipeline variable 'secondJobVar' is $(secondJobVar)"
      name: access_output_variable_from_first_job

- stage: SecondStage
  variables:
  - name: second_stage_variable
    value: $[ stageDependencies.FirstStage.FirstStageFirstJob.outputs['set_output_variable.firstJobVar'] ]
  jobs:
  - job: SecondStageFirstJob
    steps:
    - bash: |
        echo "'second_stage_variable' value is ${second_stage_variable}"
      name: access_from_second_stage_output_variable
