#trigger: none
trigger:
- main
pr: none

pool: 'Azure Pipelines'

variables:
  staticV: value_of_static_V

jobs:
- job: FirstJob
  displayName: First Job
  steps:
  - bash: |
      echo "So damn, let's start"

  - bash: |
      SOMEVAR="bla-bla-bla"
      echo ${SOMEVAR}
      echo "set output pipeline variable:"
      echo "##vso[task.setvariable variable=firstJobV;isOutput=true]this_is_the_value"
      echo "The value of the output pipeline variable 'firstJobV' is ${firstJobV}"
      echo "The scope of variable 'firstJobV' is job FirstJob"

- job: SecondJob
  displayName: Second Job
  dependsOn: ['FirstJob']
  variables:
    secondJobV: $[ dependencies.FirstJob.outputs['setVariable.firstJobV'] ] 
  steps:      
  - bash: |
      echo "The value of the dinamic pipeline variable 'secondJobV' is $secondJobV"
      echo "The scope of variable 'secondJobV' is job SecondJob"
