#trigger: none
trigger:
- main
pr: none

pool: 'Azure Pipelines'

jobs:
- job: FirstJob
  displayName: First Job
  steps:
  - bash: |
      echo "So damn, let's start"
    name: dummy_step
  - bash: |
      echo "##vso[task.setvariable variable=myJobVar]this is the same job"
    name: set_variable
  - bash: |
      echo "##vso[task.setvariable variable=myOutputJobVar;isoutput=true]this is the same job too"
    name: set_output_variable
  - bash: |
      echo $(myJobVar)
    name: access_variable
  - bash: |
      echo $(setOutput.myOutputJobVar)
    name: access_output_variable

#- job: SecondJob
#  displayName: Second Job
#  dependsOn: ['FirstJob']
#  variables:
#    secondJobV: $[ dependencies.FirstJob.outputs['setVariable.firstJobV'] ] 
#  steps:      
#  - bash: |
#      echo "The value of the dinamic pipeline variable 'secondJobV' is $secondJobV"
#      echo "The scope of variable 'secondJobV' is job SecondJob"
