#trigger: none
trigger:
- main
pr: none

pool: 'Azure Pipelines'

stages:
- stage: FirstStage
  jobs:
  - job: FirstJob
    steps:
    - bash: |
        echo "So damn, let's start"
      name: dummy_step
    - bash: |
        SOME_VAR="bla-bla-bla"
        echo "set output pipeline variable:"
        echo "##vso[task.setvariable variable=firstJobVar;isOutput=true]${SOME_VAR}"
      name: set_output_variable
    - bash: |
        echo $(set_output_variable.firstJobVar)
      name: access_output_variable

  - job: SecondJob
    dependsOn: ['FirstJob']
    variables:
      # the format for referencing an output variable from another job is dependencies.JOB.outputs['TASK.VARIABLE']
      secondJobVar: $[ dependencies.FirstJob.outputs['set_output_variable.firstJobVar'] ] 
    steps:      
    - bash: |
        echo "The value of the dinamic pipeline variable 'secondJobVar' is $(secondJobVar)"
      name: access_output_variable_from_first_job

- stage: SecondStage
  dependsOn: FirstStage
  jobs:
  - job: FirstJob
    variables:
      # At the job level, the format for referencing an output variable from another stage is stageDependencies.STAGE.JOB.outputs['TASK.VARIABLE']
      secondStageJobVar: $[ stageDependencies.FirstStage.FirstJob.outputs['set_output_variable.firstJobVar'] ]
    steps:
    - bash: |
        echo "'secondStageJobVar' value is $(secondStageJobVar)"
      name: access_first_stage_output_variable

- stage: ThirdStage
  dependsOn: FirstStage
  jobs:
  - job: FirstJob
    variables:
      # At the job level, the format for referencing an output variable from another stage is stageDependencies.STAGE.JOB.outputs['TASK.VARIABLE']
      thirdStageJobVar: $[ stageDependencies.FirstStage.FirstJob.outputs['set_output_variable.firstJobVar'] ]
    steps:
    - bash: |
        echo "'thirdStageJobVar' value is $(thirdStageJobVar)"
      name: access_first_stage_output_variable
